# model name
exp_name: 'BEV_CLR_AD'

# Training parameters
max_iters: 50000
log_freq: 100
shuffle: true
dset: 'trainval'
save_freq: 1000
batch_size: 1
grad_acc: 5
lr: 0.0003
use_scheduler: true
weight_decay: 0.0000001
nworkers: 8

# Directories
data_dir: '/../../../../../../beegfs/scratch/workspace/es_luheit04-NuScneDataset_new/es_luheit04-NuSceneDataset-1756172124/nuscenes'
custom_dataroot: 'datasets/scaled_images'
log_dir: 'logs_nuscenes'
ckpt_dir: 'model_checkpoints'
keep_latest: 75
init_dir: ''
ignore_load: null
load_step: true
load_optimizer: true
load_scheduler: true

# Data parameters
final_dim: [448, 896]  # to match //8, //14, //16 and //32 in Vit
rand_flip: false
rand_crop_and_resize: false
ncams: 6
nsweeps: 5
lidar_nsweeps: 5
grid_dim: [200, 8, 200]

# Model parameters
train_task: 'both'
use_obj_layer_only_on_map: true

encoder_type: 'dino_v2'
use_pre_scaled_imgs: false
init_query_with_image_feats: true
do_rgbcompress: true
do_shuffle_cams: true
use_multi_scale_img_feats: true
num_layers: 6

radar_encoder_type: 'voxel_net'
use_rpn_radar: false
use_radar: true
use_radar_filters: false
use_radar_encoder: true 
use_radar_occupancy_map: false
use_metaradar: false
use_shallow_metadata: true

lidar_encoder_type: 'voxel_net'
use_lidar: true  #kann aktuell noch nicht auf false gesetzt werden
use_lidar_encoder: false
use_lidar_occupancy_map: false

device_ids: [0]
freeze_dino: true
do_feat_enc_dec: true
combine_feat_init_w_learned_q: true
model_type: 'transformer'
learnable_fuse_query: true

# wandb
group: 'BEV_CLR_AD'
notes: 'BEV_CLR_AD model: radar encoding, LiDAR encoding, DINO as image backbone, fusion and lifting based on transformer,
6 blocks, radar init, image init, multiscale feats, enc-dec, radar and LiDAR as query for fusion,
with learnable queries'
name: 'BEVCar'
